import { auth } from "@/lib/auth";
import { headers, cookies } from "next/headers";
import PageHeader from "@/components/PageHeader";
import Link from "next/link";

export default async function TermsPage() {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  const cookieStore = await cookies();
  const lang = (session?.user as any)?.language === "zh" ? "zh"
    : cookieStore.get("NEXT_LOCALE")?.value === "zh" ? "zh"
    : "en";

  const t = {
    title: lang === "zh" ? "服务条款" : "Terms of Service",
    lastUpdated: lang === "zh" ? "最后更新：2026年6月9日" : "Last updated: June 9, 2026",
    intro: lang === "zh"
      ? "欢迎使用 Swoonly。请仔细阅读以下条款。使用本服务即表示您同意这些条款。如果您不同意，请勿使用本服务。"
      : "Welcome to Swoonly. Please read these terms carefully. By using the Service, you agree to these terms. If you do not agree, do not use the Service.",

    sections: [
      {
        title: lang === "zh" ? "1. 服务描述" : "1. Service Description",
        content: lang === "zh"
          ? [
              "Swoonly 是一款 AI 驱动的虚拟伴侣聊天应用。用户可以选择预设角色进行文字对话，角色会以语音回复。",
              "角色均由 AI 生成，并非真实人物。您理解并接受所有对话均由 AI 模型生成，我们不对 AI 生成内容的准确性、适当性或完整性负责。",
              "免费用户每天限发 50 条消息。付费订阅用户可在订阅期内无限聊天。",
            ]
          : [
              "Swoonly is an AI-powered virtual companion chat application. Users choose from preset characters for text conversations, and characters reply with voice.",
              "All characters are AI-generated and not real people. You understand and accept that all conversations are generated by AI models, and we are not responsible for the accuracy, appropriateness, or completeness of AI-generated content.",
              "Free users are limited to 50 messages per day. Paid subscribers enjoy unlimited chat during their subscription period.",
            ],
      },
      {
        title: lang === "zh" ? "2. 用户账户" : "2. User Accounts",
        content: lang === "zh"
          ? [
              "您必须年满 13 岁才能创建账户。",
              "您可以使用邮箱注册或 Google 账户登录。",
              "您对账户下的所有活动负责，包括 AI 对话内容。",
              "请保护您的账户凭据安全。如发现未经授权的使用，请立即通知我们。",
              "我们保留因违反这些条款而暂停或终止账户的权利。",
            ]
          : [
              "You must be at least 13 years old to create an account.",
              "You may register with email or sign in with a Google account.",
              "You are responsible for all activity under your account, including AI conversation content.",
              "Please keep your account credentials secure. Notify us immediately of any unauthorized use.",
              "We reserve the right to suspend or terminate accounts for violation of these terms.",
            ],
      },
      {
        title: lang === "zh" ? "3. 可接受使用" : "3. Acceptable Use",
        content: lang === "zh"
          ? [
              "利用本服务生成或传播违法、色情、仇恨、骚扰、暴力或其他不当内容。",
              "尝试逆向工程、破解或未经授权访问本服务的任何部分。",
              "使用自动化工具（机器人、脚本等）大量发送消息或创建账户。",
              "将本服务用于任何非法目的或侵犯他人权利的活动。",
              "冒充他人身份或虚构与他人、组织的关系。",
              "违反者将被立即暂停或永久封禁账户，不退还已付费用。",
            ]
          : [
              "Use the Service to generate or disseminate illegal, pornographic, hateful, harassing, violent, or otherwise inappropriate content.",
              "Attempt to reverse engineer, hack, or gain unauthorized access to any part of the Service.",
              "Use automated tools (bots, scripts, etc.) to send bulk messages or create accounts.",
              "Use the Service for any illegal purpose or activities that infringe on others' rights.",
              "Impersonate others or fabricate relationships with individuals or organizations.",
              "Violators will have their accounts suspended or permanently banned without refund of paid fees.",
            ],
      },
      {
        title: lang === "zh" ? "4. 知识产权" : "4. Intellectual Property",
        content: lang === "zh"
          ? [
              "Swoonly 的名称、Logo、界面设计和源代码是我们的知识产权。未经许可不得复制或使用。",
              "角色设定、头像图片和系统提示词是我们的原创内容。",
              "AI 生成的对话内容：您拥有自己输入内容的所有权，但 AI 生成的回复属于本服务。您可以因个人非商业用途保留对话记录。",
            ]
          : [
              "The Swoonly name, logo, interface design, and source code are our intellectual property. Do not copy or use without permission.",
              "Character settings, avatar images, and system prompts are our original content.",
              "AI-generated conversation content: You own your input content, but AI-generated replies belong to the Service. You may keep conversation records for personal, non-commercial use.",
            ],
      },
      {
        title: lang === "zh" ? "5. 付费与订阅" : "5. Payments & Subscriptions",
        content: lang === "zh"
          ? [
              "订阅费用以购买时显示的金额为准，可能因地区而异。",
              "所有付款通过 Stripe 安全处理。我们不储存您的完整支付信息。",
              "订阅默认自动续费，除非您在当期结束前取消。",
              "取消订阅仅停止未来续费，已支付的当期费用不予退还，除非适用法律另有规定。",
              "我们保留调整订阅价格的权利。价格变更会提前通知，不会影响已购买的订阅期。",
            ]
          : [
              "Subscription fees are as displayed at the time of purchase and may vary by region.",
              "All payments are securely processed by Stripe. We do not store your full payment details.",
              "Subscriptions auto-renew by default unless you cancel before the current period ends.",
              "Cancellation only stops future renewals. Current period fees are non-refundable unless required by applicable law.",
              "We reserve the right to adjust subscription pricing. Price changes will be announced in advance and will not affect already-purchased subscription periods.",
            ],
      },
      {
        title: lang === "zh" ? "6. 免责声明" : "6. Disclaimer of Warranties",
        content: lang === "zh"
          ? [
              "本服务按\"现状\"提供，不作任何明示或暗示的保证。",
              "我们不保证服务不中断、完全安全或零错误。",
              "AI 生成的回复可能含有不准确、不适当或冒犯性内容。您自行承担使用 AI 回复的风险。",
              "因网络故障、维护或不可抗力导致的服务中断，我们不承担责任。",
            ]
          : [
              "The Service is provided \"as is\" without any express or implied warranties.",
              "We do not guarantee the Service will be uninterrupted, fully secure, or error-free.",
              "AI-generated replies may contain inaccurate, inappropriate, or offensive content. You assume the risk of using AI replies.",
              "We are not liable for service interruptions caused by network failures, maintenance, or force majeure events.",
            ],
      },
      {
        title: lang === "zh" ? "7. 责任限制" : "7. Limitation of Liability",
        content: lang === "zh"
          ? [
              "在法律允许的最大范围内，Swoonly 及其运营方对于因使用本服务而产生的任何间接、附带、特殊或结果性损害概不负责。",
              "我们对于任何索赔的总责任不超过您在索赔发生前 12 个月内支付给我们的费用总额。",
            ]
          : [
              "To the maximum extent permitted by law, Swoonly and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from use of the Service.",
              "Our total liability for any claim shall not exceed the total fees you paid to us in the 12 months preceding the claim.",
            ],
      },
      {
        title: lang === "zh" ? "8. 终止" : "8. Termination",
        content: lang === "zh"
          ? [
              "您可以随时停止使用服务并删除账户。",
              "我们保留在您违反条款时暂停或终止账户的权利。",
              "终止后，您将失去对聊天记录的访问权限。我们可能按法律要求保留部分数据一段时间。",
            ]
          : [
              "You may stop using the Service and delete your account at any time.",
              "We reserve the right to suspend or terminate accounts that violate these terms.",
              "Upon termination, you lose access to your chat history. We may retain certain data as required by law for a limited period.",
            ],
      },
      {
        title: lang === "zh" ? "9. 条款变更" : "9. Changes to Terms",
        content: lang === "zh"
          ? [
              "我们可能会修改这些条款。重大变更将通过电子邮件或服务内通知告知。",
              "变更通知发布后继续使用服务即表示您接受新条款。",
            ]
          : [
              "We may modify these terms. Material changes will be communicated via email or in-service notice.",
              "Continued use of the Service after changes are posted constitutes acceptance of the new terms.",
            ],
      },
      {
        title: lang === "zh" ? "10. 适用法律" : "10. Governing Law",
        content: lang === "zh"
          ? [
              "本条款受适用法律管辖，不适用法律冲突原则。",
              "因本服务产生的任何争议应通过友好协商解决。协商不成的，提交有管辖权的法院裁决。",
            ]
          : [
              "These terms are governed by applicable laws without regard to conflict of law principles.",
              "Any disputes arising from the Service shall be resolved through friendly negotiation. If negotiation fails, the dispute shall be submitted to a court of competent jurisdiction.",
            ],
      },
      {
        title: lang === "zh" ? "11. 联系我们" : "11. Contact Us",
        content: lang === "zh"
          ? [
              "如果您对本服务条款有任何疑问，请发送邮件至：support@swoonly.online",
            ]
          : [
              "If you have any questions about these Terms of Service, please email: support@swoonly.online",
            ],
      },
    ],
  };

  return (
    <div className="min-h-screen flex flex-col">
      <PageHeader lang={lang} loggedIn={!!session} userName={session?.user?.name} />

      <main className="flex-1 max-w-2xl mx-auto px-4 py-16 w-full">
        <h1 className="font-display font-bold text-[var(--text-primary)] mb-2" style={{ fontSize: "clamp(1.5rem, 3vw, 2.25rem)" }}>
          {t.title}
        </h1>
        <p className="text-[var(--text-muted)] text-sm mb-10">{t.lastUpdated}</p>

        <p className="text-[var(--text-secondary)] text-sm leading-relaxed mb-10">{t.intro}</p>

        <div className="space-y-10">
          {t.sections.map((section, i) => (
            <section key={i}>
              <h2 className="font-display font-semibold text-[var(--text-primary)] text-base mb-3">
                {section.title}
              </h2>
              <ul className="list-disc list-inside space-y-2">
                {section.content.map((item, j) => (
                  <li key={j} className="text-[var(--text-secondary)] text-sm leading-relaxed">{item}</li>
                ))}
              </ul>
            </section>
          ))}
        </div>

        <div className="mt-16 pt-8 border-t border-[var(--border-subtle)]">
          <Link
            href="/"
            className="text-sm text-[var(--accent-rose)] hover:text-[var(--accent-warm)] transition-colors"
          >
            {lang === "zh" ? "← 返回首页" : "← Back to Home"}
          </Link>
        </div>
      </main>
    </div>
  );
}
